#!/bin/sh

# Change `style.css` or `style.min.css` to whatever you would like your compiled
# stylesheet to be called. Do not rename `system.scss` or alter references to it.

# No minification
#sass --watch system.scss:style.css --style expanded

# Minification
#sass --watch system.scss:style.css --style compressed

sass --watch system.scss:grid.min.css --style expanded #compressed

exit 0
